# encoding: UTF-8

module CitySeed
  #puts " -- Adding cities"
  #DictionaryCity.create(:name => 'Шебекино', :dictionary_region_id => 17)
  #DictionaryCity.create(:name => 'Строитель', :dictionary_region_id => 17)
  #DictionaryCity.create(:name => 'Старый Оскол', :dictionary_region_id => 17)
  #DictionaryCity.create(:name => 'Новый Оскол', :dictionary_region_id => 17)
  #DictionaryCity.create(:name => 'Короча', :dictionary_region_id => 17)
  #DictionaryCity.create(:name => 'Губкин', :dictionary_region_id => 17)
  #DictionaryCity.create(:name => 'Грайворон', :dictionary_region_id => 17)
  #DictionaryCity.create(:name => 'Валуйки', :dictionary_region_id => 17)
  #DictionaryCity.create(:name => 'Бирюч', :dictionary_region_id => 17)
  #DictionaryCity.create(:name => 'Белгород', :dictionary_region_id => 17)
  #DictionaryCity.create(:name => 'Алексеевка', :dictionary_region_id => 17)

  #DictionaryCity.create(:name => 'Фокино', :dictionary_region_id => 16)
  #DictionaryCity.create(:name => 'Унеча', :dictionary_region_id => 16)
  #DictionaryCity.create(:name => 'Трубчевск', :dictionary_region_id => 16)
  #DictionaryCity.create(:name => 'Сураж', :dictionary_region_id => 16)
  #DictionaryCity.create(:name => 'Стародуб', :dictionary_region_id => 16)
  #DictionaryCity.create(:name => 'Сельцо', :dictionary_region_id => 16)
  #DictionaryCity.create(:name => 'Севск', :dictionary_region_id => 16)
  #DictionaryCity.create(:name => 'Почеп', :dictionary_region_id => 16)
  #DictionaryCity.create(:name => 'Новозыбков', :dictionary_region_id => 16)
  #DictionaryCity.create(:name => 'Мглин', :dictionary_region_id => 16)
  #DictionaryCity.create(:name => 'Клинцы', :dictionary_region_id => 16)
  #DictionaryCity.create(:name => 'Карачев', :dictionary_region_id => 16)
  #DictionaryCity.create(:name => 'Злынка', :dictionary_region_id => 16)
  #DictionaryCity.create(:name => 'Жуковка', :dictionary_region_id => 16)
  #DictionaryCity.create(:name => 'Дятьково', :dictionary_region_id => 16)
  #DictionaryCity.create(:name => 'Брянск', :dictionary_region_id => 16)

  #DictionaryCity.create(:name => 'Юрьев-Польский', :dictionary_region_id => 15)
  #DictionaryCity.create(:name => 'Суздаль', :dictionary_region_id => 15)
  #DictionaryCity.create(:name => 'Судогда', :dictionary_region_id => 15)
  #DictionaryCity.create(:name => 'Струнино', :dictionary_region_id => 15)
  #DictionaryCity.create(:name => 'Собинка', :dictionary_region_id => 15)
  #DictionaryCity.create(:name => 'Радужный', :dictionary_region_id => 15)
  #DictionaryCity.create(:name => 'Покров', :dictionary_region_id => 15)
  #DictionaryCity.create(:name => 'Петушки', :dictionary_region_id => 15)
  #DictionaryCity.create(:name => 'Муром', :dictionary_region_id => 15)
  #DictionaryCity.create(:name => 'Меленки', :dictionary_region_id => 15)
  #DictionaryCity.create(:name => 'Лакинск', :dictionary_region_id => 15)
  #DictionaryCity.create(:name => 'Костерево', :dictionary_region_id => 15)
  #DictionaryCity.create(:name => 'Курлово', :dictionary_region_id => 15)
  #DictionaryCity.create(:name => 'Ковров', :dictionary_region_id => 15)
  #DictionaryCity.create(:name => 'Киржач', :dictionary_region_id => 15)
  #DictionaryCity.create(:name => 'Карабаново', :dictionary_region_id => 15)
  #DictionaryCity.create(:name => 'Камешково', :dictionary_region_id => 15)
  #DictionaryCity.create(:name => 'Гусь-Хрустальный', :dictionary_region_id => 15)
  #DictionaryCity.create(:name => 'Гороховец', :dictionary_region_id => 15)
  #DictionaryCity.create(:name => 'Вязники', :dictionary_region_id => 15)
  #DictionaryCity.create(:name => 'Владимир', :dictionary_region_id => 15)
  #DictionaryCity.create(:name => 'Александров', :dictionary_region_id => 15)

  #DictionaryCity.create(:name => 'Эртиль', :dictionary_region_id => 14)
  #DictionaryCity.create(:name => 'Семилуки', :dictionary_region_id => 14)
  #DictionaryCity.create(:name => 'Россошь', :dictionary_region_id => 14)
  #DictionaryCity.create(:name => 'Поворино', :dictionary_region_id => 14)
  #DictionaryCity.create(:name => 'Павловск', :dictionary_region_id => 14)
  #DictionaryCity.create(:name => 'Острогожск', :dictionary_region_id => 14)
  #DictionaryCity.create(:name => 'Новохоперск', :dictionary_region_id => 14)
  #DictionaryCity.create(:name => 'Нововоронеж', :dictionary_region_id => 14)
  #DictionaryCity.create(:name => 'Лиски', :dictionary_region_id => 14)
  #DictionaryCity.create(:name => 'Калач', :dictionary_region_id => 14)
  #DictionaryCity.create(:name => 'Воронеж', :dictionary_region_id => 14)
  #DictionaryCity.create(:name => 'Бутурлиновка', :dictionary_region_id => 14)
  #DictionaryCity.create(:name => 'Богучар', :dictionary_region_id => 14)
  #DictionaryCity.create(:name => 'Бобров', :dictionary_region_id => 14)

  #DictionaryCity.create(:name => 'Юрьевец', :dictionary_region_id => 13)
  #DictionaryCity.create(:name => 'Южа', :dictionary_region_id => 13)
  #DictionaryCity.create(:name => 'Шуя', :dictionary_region_id => 13)
  #DictionaryCity.create(:name => 'Фурманов', :dictionary_region_id => 13)
  #DictionaryCity.create(:name => 'Тейково', :dictionary_region_id => 13)
  #DictionaryCity.create(:name => 'Родники', :dictionary_region_id => 13)
  #DictionaryCity.create(:name => 'Пучеж', :dictionary_region_id => 13)
  #DictionaryCity.create(:name => 'Приволжск', :dictionary_region_id => 13)
  #DictionaryCity.create(:name => 'Плёс', :dictionary_region_id => 13)
  #DictionaryCity.create(:name => 'Наволоки', :dictionary_region_id => 13)
  #DictionaryCity.create(:name => 'Кохма', :dictionary_region_id => 13)
  #DictionaryCity.create(:name => 'Комсомольск', :dictionary_region_id => 13)
  #DictionaryCity.create(:name => 'Кинешма', :dictionary_region_id => 13)
  #DictionaryCity.create(:name => 'Иваново', :dictionary_region_id => 13)
  #DictionaryCity.create(:name => 'Заволжск', :dictionary_region_id => 13)
  #DictionaryCity.create(:name => 'Гаврилов Посад', :dictionary_region_id => 13)
  #DictionaryCity.create(:name => 'Вичуга', :dictionary_region_id => 13)

  #DictionaryCity.create(:name => 'Юхнов', :dictionary_region_id => 12)
  #DictionaryCity.create(:name => 'Таруса', :dictionary_region_id => 12)
  #DictionaryCity.create(:name => 'Сухиничи', :dictionary_region_id => 12)
  #DictionaryCity.create(:name => 'Спас-Деменск', :dictionary_region_id => 12)
  #DictionaryCity.create(:name => 'Сосенский', :dictionary_region_id => 12)
  #DictionaryCity.create(:name => 'Обнинск', :dictionary_region_id => 12)
  #DictionaryCity.create(:name => 'Мосальск', :dictionary_region_id => 12)
  #DictionaryCity.create(:name => 'Мещовск', :dictionary_region_id => 12)
  #DictionaryCity.create(:name => 'Медынь', :dictionary_region_id => 12)
  #DictionaryCity.create(:name => 'Малоярославец', :dictionary_region_id => 12)
  #DictionaryCity.create(:name => 'Людиново', :dictionary_region_id => 12)
  #DictionaryCity.create(:name => 'Кремёнки', :dictionary_region_id => 12)
  #DictionaryCity.create(:name => 'Кондрово', :dictionary_region_id => 12)
  #DictionaryCity.create(:name => 'Козельск', :dictionary_region_id => 12)
  #DictionaryCity.create(:name => 'Киров', :dictionary_region_id => 12)
  #DictionaryCity.create(:name => 'Калуга', :dictionary_region_id => 12)
  #DictionaryCity.create(:name => 'Жуков', :dictionary_region_id => 12)
  #DictionaryCity.create(:name => 'Жиздра', :dictionary_region_id => 12)
  #DictionaryCity.create(:name => 'Ермолино', :dictionary_region_id => 12)
  #DictionaryCity.create(:name => 'Боровск', :dictionary_region_id => 12)
  #DictionaryCity.create(:name => 'Белоусово', :dictionary_region_id => 12)
  #DictionaryCity.create(:name => 'Балабаново', :dictionary_region_id => 12)

  #DictionaryCity.create(:name => 'Курган', :dictionary_region_id => 60)
  #DictionaryCity.create(:name => 'Куртамыш', :dictionary_region_id => 60)
  #DictionaryCity.create(:name => 'Макушино', :dictionary_region_id => 60)
  #DictionaryCity.create(:name => 'Петухово', :dictionary_region_id => 60)
  #DictionaryCity.create(:name => 'Шадринск', :dictionary_region_id => 60)
  #DictionaryCity.create(:name => 'Шумиха', :dictionary_region_id => 60)
  #DictionaryCity.create(:name => 'Щучье', :dictionary_region_id => 60)
  #DictionaryCity.create(:name => 'Катайск', :dictionary_region_id => 60)
  #DictionaryCity.create(:name => 'Далматово', :dictionary_region_id => 60)

  #DictionaryCity.create(:name => 'Ульяновск', :dictionary_region_id => 41)
  #DictionaryCity.create(:name => 'Сенгилей', :dictionary_region_id => 41)
  #DictionaryCity.create(:name => 'Новоульяновск', :dictionary_region_id => 41)
  #DictionaryCity.create(:name => 'Инза', :dictionary_region_id => 41)
  #DictionaryCity.create(:name => 'Димитровград', :dictionary_region_id => 41)
  #DictionaryCity.create(:name => 'Барыш', :dictionary_region_id => 41)

  #DictionaryCity.create(:name => 'Энгельс', :dictionary_region_id => 42)
  #DictionaryCity.create(:name => 'Шиханы', :dictionary_region_id => 42)
  #DictionaryCity.create(:name => 'Хвалынск', :dictionary_region_id => 42)
  #DictionaryCity.create(:name => 'Саратов', :dictionary_region_id => 42)
  #DictionaryCity.create(:name => 'Ртищево', :dictionary_region_id => 42)
  #DictionaryCity.create(:name => 'Пугачёв', :dictionary_region_id => 42)
  #DictionaryCity.create(:name => 'Петровск', :dictionary_region_id => 42)
  #DictionaryCity.create(:name => 'Новоузенск', :dictionary_region_id => 42)
  #DictionaryCity.create(:name => 'Маркс', :dictionary_region_id => 42)
  #DictionaryCity.create(:name => 'Красный Кут', :dictionary_region_id => 42)
  #DictionaryCity.create(:name => 'Калининск', :dictionary_region_id => 42)
  #DictionaryCity.create(:name => 'Ершов', :dictionary_region_id => 42)
  #DictionaryCity.create(:name => 'Вольск', :dictionary_region_id => 42)
  #DictionaryCity.create(:name => 'Балашов', :dictionary_region_id => 42)
  #DictionaryCity.create(:name => 'Балаково', :dictionary_region_id => 42)
  #DictionaryCity.create(:name => 'Аткарск', :dictionary_region_id => 42)
  #DictionaryCity.create(:name => 'Аркадак', :dictionary_region_id => 42)

  #DictionaryCity.create(:name => 'Чапаевск', :dictionary_region_id => 43)
  #DictionaryCity.create(:name => 'Тольятти', :dictionary_region_id => 43)
  #DictionaryCity.create(:name => 'Сызрань', :dictionary_region_id => 43)
  #DictionaryCity.create(:name => 'Самара', :dictionary_region_id => 43)
  #DictionaryCity.create(:name => 'Похвистнево', :dictionary_region_id => 43)
  #DictionaryCity.create(:name => 'Отрадный', :dictionary_region_id => 43)
  #DictionaryCity.create(:name => 'Октябрьск', :dictionary_region_id => 43)
  #DictionaryCity.create(:name => 'Новокуйбышевск', :dictionary_region_id => 43)
  #DictionaryCity.create(:name => 'Нефтегорск', :dictionary_region_id => 43)
  #DictionaryCity.create(:name => 'Кинель', :dictionary_region_id => 43)
  #DictionaryCity.create(:name => 'Жигулёвск', :dictionary_region_id => 43)

  #DictionaryCity.create(:name => 'Сурск', :dictionary_region_id => 44)
  #DictionaryCity.create(:name => 'Спасск', :dictionary_region_id => 44)
  #DictionaryCity.create(:name => 'Сердобск', :dictionary_region_id => 44)
  #DictionaryCity.create(:name => 'Пенза', :dictionary_region_id => 44)
  #DictionaryCity.create(:name => 'Нижний Ломов', :dictionary_region_id => 44)
  #DictionaryCity.create(:name => 'Кузнецк', :dictionary_region_id => 44)
  #DictionaryCity.create(:name => 'Каменка', :dictionary_region_id => 44)
  #DictionaryCity.create(:name => 'Заречный', :dictionary_region_id => 44)
  #DictionaryCity.create(:name => 'Городище', :dictionary_region_id => 44)
  #DictionaryCity.create(:name => 'Белинский', :dictionary_region_id => 44)
  #DictionaryCity.create(:name => 'Никольск', :dictionary_region_id => 44)

  #DictionaryCity.create(:name => 'Ясный', :dictionary_region_id => 45)
  #DictionaryCity.create(:name => 'Сорочинск', :dictionary_region_id => 45)
  #DictionaryCity.create(:name => 'Соль-Илецк', :dictionary_region_id => 45)
  #DictionaryCity.create(:name => 'Орск', :dictionary_region_id => 45)
  #DictionaryCity.create(:name => 'Оренбург', :dictionary_region_id => 45)
  #DictionaryCity.create(:name => 'Новотроицк', :dictionary_region_id => 45)
  #DictionaryCity.create(:name => 'Медногорск', :dictionary_region_id => 45)
  #DictionaryCity.create(:name => 'Кувандык', :dictionary_region_id => 45)
  #DictionaryCity.create(:name => 'Гай', :dictionary_region_id => 45)
  #DictionaryCity.create(:name => 'Бузулук', :dictionary_region_id => 45)
  #DictionaryCity.create(:name => 'Бугуруслан', :dictionary_region_id => 45)
  #DictionaryCity.create(:name => 'Абдулино', :dictionary_region_id => 45)

  #DictionaryCity.create(:name => 'Шахунья', :dictionary_region_id => 48)
  #DictionaryCity.create(:name => 'Чкаловск', :dictionary_region_id => 48)
  #DictionaryCity.create(:name => 'Урень', :dictionary_region_id => 48)
  #DictionaryCity.create(:name => 'Сергач', :dictionary_region_id => 48)
  #DictionaryCity.create(:name => 'Семёнов', :dictionary_region_id => 48)
  #DictionaryCity.create(:name => 'Саров', :dictionary_region_id => 48)
  #DictionaryCity.create(:name => 'Перевоз', :dictionary_region_id => 48)
  #DictionaryCity.create(:name => 'Первомайск', :dictionary_region_id => 48)
  #DictionaryCity.create(:name => 'Павлово', :dictionary_region_id => 48)
  #DictionaryCity.create(:name => 'Нижний Новгород', :dictionary_region_id => 48)
  #DictionaryCity.create(:name => 'Навашино', :dictionary_region_id => 48)
  #DictionaryCity.create(:name => 'Лысково', :dictionary_region_id => 48)
  #DictionaryCity.create(:name => 'Лукоянов', :dictionary_region_id => 48)
  #DictionaryCity.create(:name => 'Кулебаки', :dictionary_region_id => 48)
  #DictionaryCity.create(:name => 'Кстово', :dictionary_region_id => 48)
  #DictionaryCity.create(:name => 'Княгинино', :dictionary_region_id => 48)
  #DictionaryCity.create(:name => 'Заволжье', :dictionary_region_id => 48)
  #DictionaryCity.create(:name => 'Дзержинск', :dictionary_region_id => 48)
  #DictionaryCity.create(:name => 'Городец', :dictionary_region_id => 48)
  #DictionaryCity.create(:name => 'Горбатов', :dictionary_region_id => 48)
  #DictionaryCity.create(:name => 'Выкса', :dictionary_region_id => 48)
  #DictionaryCity.create(:name => 'Ворсма', :dictionary_region_id => 48)
  #DictionaryCity.create(:name => 'Володарск', :dictionary_region_id => 48)
  #DictionaryCity.create(:name => 'Ветлуга', :dictionary_region_id => 48)
  #DictionaryCity.create(:name => 'Бор', :dictionary_region_id => 48)
  #DictionaryCity.create(:name => 'Богородск', :dictionary_region_id => 48)
  #DictionaryCity.create(:name => 'Балахна', :dictionary_region_id => 48)
  #DictionaryCity.create(:name => 'Арзамас', :dictionary_region_id => 48)

  #DictionaryCity.create(:name => 'Яранск', :dictionary_region_id => 47)
  #DictionaryCity.create(:name => 'Уржум', :dictionary_region_id => 47)
  #DictionaryCity.create(:name => 'Сосновка', :dictionary_region_id => 47)
  #DictionaryCity.create(:name => 'Слободской', :dictionary_region_id => 47)
  #DictionaryCity.create(:name => 'Орлов', :dictionary_region_id => 47)
  #DictionaryCity.create(:name => 'Омутнинск', :dictionary_region_id => 47)
  #DictionaryCity.create(:name => 'Нолинск', :dictionary_region_id => 47)
  #DictionaryCity.create(:name => 'Мураши', :dictionary_region_id => 47)
  #DictionaryCity.create(:name => 'Малмыж', :dictionary_region_id => 47)
  #DictionaryCity.create(:name => 'Луза', :dictionary_region_id => 47)
  #DictionaryCity.create(:name => 'Котельнич', :dictionary_region_id => 47)
  #DictionaryCity.create(:name => 'Кирс', :dictionary_region_id => 47)
  #DictionaryCity.create(:name => 'Кирово-Чепецк', :dictionary_region_id => 47)
  #DictionaryCity.create(:name => 'Зуевка', :dictionary_region_id => 47)
  #DictionaryCity.create(:name => 'Вятские Поляны', :dictionary_region_id => 47)
  #DictionaryCity.create(:name => 'Белая Холуница', :dictionary_region_id => 47)
  #DictionaryCity.create(:name => 'Киров', :dictionary_region_id => 47)

  #DictionaryCity.create(:name => 'Чусовой', :dictionary_region_id => 46)
  #DictionaryCity.create(:name => 'Чернушка', :dictionary_region_id => 46)
  #DictionaryCity.create(:name => 'Чёрмоз', :dictionary_region_id => 46)
  #DictionaryCity.create(:name => 'Чердынь', :dictionary_region_id => 46)
  #DictionaryCity.create(:name => 'Чайковский', :dictionary_region_id => 46)
  #DictionaryCity.create(:name => 'Усолье', :dictionary_region_id => 46)
  #DictionaryCity.create(:name => 'Соликамск', :dictionary_region_id => 46)
  #DictionaryCity.create(:name => 'Пермь', :dictionary_region_id => 46)
  #DictionaryCity.create(:name => 'Очёр', :dictionary_region_id => 46)
  #DictionaryCity.create(:name => 'Оханск', :dictionary_region_id => 46)
  #DictionaryCity.create(:name => 'Оса', :dictionary_region_id => 46)
  #DictionaryCity.create(:name => 'Нытва', :dictionary_region_id => 46)
  #DictionaryCity.create(:name => 'Лысьва', :dictionary_region_id => 46)
  #DictionaryCity.create(:name => 'Кунгур', :dictionary_region_id => 46)
  #DictionaryCity.create(:name => 'Кудымкар', :dictionary_region_id => 46)
  #DictionaryCity.create(:name => 'Краснокамск', :dictionary_region_id => 46)
  #DictionaryCity.create(:name => 'Красновишерск', :dictionary_region_id => 46)
  #DictionaryCity.create(:name => 'Кизел', :dictionary_region_id => 46)
  #DictionaryCity.create(:name => 'Добрянка', :dictionary_region_id => 46)
  #DictionaryCity.create(:name => 'Губаха', :dictionary_region_id => 46)
  #DictionaryCity.create(:name => 'Гремячинск', :dictionary_region_id => 46)
  #DictionaryCity.create(:name => 'Горнозаводск', :dictionary_region_id => 46)
  #DictionaryCity.create(:name => 'Верещагино', :dictionary_region_id => 46)
  #DictionaryCity.create(:name => 'Березники', :dictionary_region_id => 46)
  #DictionaryCity.create(:name => 'Александровск', :dictionary_region_id => 46)

  #DictionaryCity.create(:name => 'Ядрин', :dictionary_region_id => 49)
  #DictionaryCity.create(:name => 'Шумерля', :dictionary_region_id => 49)
  #DictionaryCity.create(:name => 'Чебоксары', :dictionary_region_id => 49)
  #DictionaryCity.create(:name => 'Цивильск', :dictionary_region_id => 49)
  #DictionaryCity.create(:name => 'Новочебоксарск', :dictionary_region_id => 49)
  #DictionaryCity.create(:name => 'Мариинский Посад', :dictionary_region_id => 49)
  #DictionaryCity.create(:name => 'Козловка', :dictionary_region_id => 49)
  #DictionaryCity.create(:name => 'Канаш', :dictionary_region_id => 49)
  #DictionaryCity.create(:name => 'Алатырь', :dictionary_region_id => 49)

  #DictionaryCity.create(:name => 'Сарапул', :dictionary_region_id => 50)
  #DictionaryCity.create(:name => 'Можга', :dictionary_region_id => 50)
  #DictionaryCity.create(:name => 'Камбарка', :dictionary_region_id => 50)
  #DictionaryCity.create(:name => 'Ижевск', :dictionary_region_id => 50)
  #DictionaryCity.create(:name => 'Глазов', :dictionary_region_id => 50)
  #DictionaryCity.create(:name => 'Воткинск', :dictionary_region_id => 50)

  #DictionaryCity.create(:name => 'Чистополь', :dictionary_region_id => 51)
  #DictionaryCity.create(:name => 'Тетюши', :dictionary_region_id => 51)
  #DictionaryCity.create(:name => 'Нурлат', :dictionary_region_id => 51)
  #DictionaryCity.create(:name => 'Нижнекамск', :dictionary_region_id => 51)
  #DictionaryCity.create(:name => 'Набережные Челны', :dictionary_region_id => 51)
  #DictionaryCity.create(:name => 'Мензелинск', :dictionary_region_id => 51)
  #DictionaryCity.create(:name => 'Менделеевск', :dictionary_region_id => 51)
  #DictionaryCity.create(:name => 'Мамадыш', :dictionary_region_id => 51)
  #DictionaryCity.create(:name => 'Лениногорск', :dictionary_region_id => 51)
  #DictionaryCity.create(:name => 'Казань', :dictionary_region_id => 51)
  #DictionaryCity.create(:name => 'Зеленодольск', :dictionary_region_id => 51)
  #DictionaryCity.create(:name => 'Заинск', :dictionary_region_id => 51)
  #DictionaryCity.create(:name => 'Елабуга', :dictionary_region_id => 51)
  #DictionaryCity.create(:name => 'Буинск', :dictionary_region_id => 51)
  #DictionaryCity.create(:name => 'Бугульма', :dictionary_region_id => 51)
  #DictionaryCity.create(:name => 'Болгар', :dictionary_region_id => 51)
  #DictionaryCity.create(:name => 'Бавлы', :dictionary_region_id => 51)
  #DictionaryCity.create(:name => 'Альметьевск', :dictionary_region_id => 51)
  #DictionaryCity.create(:name => 'Азнакаево', :dictionary_region_id => 51)
  #DictionaryCity.create(:name => 'Агрыз', :dictionary_region_id => 51)
  #DictionaryCity.create(:name => 'Лаишево', :dictionary_region_id => 51)
  #DictionaryCity.create(:name => 'Арск', :dictionary_region_id => 51)

  #DictionaryCity.create(:name => 'Темников', :dictionary_region_id => 53)
  #DictionaryCity.create(:name => 'Саранск', :dictionary_region_id => 53)
  #DictionaryCity.create(:name => 'Рузаевка', :dictionary_region_id => 53)
  #DictionaryCity.create(:name => 'Ковылкино', :dictionary_region_id => 53)
  #DictionaryCity.create(:name => 'Инсар', :dictionary_region_id => 53)
  #DictionaryCity.create(:name => 'Ардатов', :dictionary_region_id => 53)
  #DictionaryCity.create(:name => 'Краснослободск', :dictionary_region_id => 53)

  #DictionaryCity.create(:name => 'Козьмодемьянск', :dictionary_region_id => 52)
  #DictionaryCity.create(:name => 'Йошкар-Ола', :dictionary_region_id => 52)
  #DictionaryCity.create(:name => 'Звенигово', :dictionary_region_id => 52)
  #DictionaryCity.create(:name => 'Волжск', :dictionary_region_id => 52)

  #DictionaryCity.create(:name => 'Янаул', :dictionary_region_id => 54)
  #DictionaryCity.create(:name => 'Учалы', :dictionary_region_id => 54)
  #DictionaryCity.create(:name => 'Уфа', :dictionary_region_id => 54)
  #DictionaryCity.create(:name => 'Туймазы', :dictionary_region_id => 54)
  #DictionaryCity.create(:name => 'Стерлитамак', :dictionary_region_id => 54)
  #DictionaryCity.create(:name => 'Сибай', :dictionary_region_id => 54)
  #DictionaryCity.create(:name => 'Салават', :dictionary_region_id => 54)
  #DictionaryCity.create(:name => 'Октябрьский', :dictionary_region_id => 54)
  #DictionaryCity.create(:name => 'Нефтекамск', :dictionary_region_id => 54)
  #DictionaryCity.create(:name => 'Мелеуз', :dictionary_region_id => 54)
  #DictionaryCity.create(:name => 'Межгорье', :dictionary_region_id => 54)
  #DictionaryCity.create(:name => 'Кумертау', :dictionary_region_id => 54)
  #DictionaryCity.create(:name => 'Ишимбай', :dictionary_region_id => 54)
  #DictionaryCity.create(:name => 'Дюртюли', :dictionary_region_id => 54)
  #DictionaryCity.create(:name => 'Давлеканово', :dictionary_region_id => 54)
  #DictionaryCity.create(:name => 'Благовещенск', :dictionary_region_id => 54)
  #DictionaryCity.create(:name => 'Бирск', :dictionary_region_id => 54)
  #DictionaryCity.create(:name => 'Белорецк', :dictionary_region_id => 54)
  #DictionaryCity.create(:name => 'Белебей', :dictionary_region_id => 54)
  #DictionaryCity.create(:name => 'Баймак', :dictionary_region_id => 54)
  #DictionaryCity.create(:name => 'Агидель', :dictionary_region_id => 54)

  #DictionaryCity.create(:name => 'Ставрополь', :dictionary_region_id => 35)
  #DictionaryCity.create(:name => 'Светлоград', :dictionary_region_id => 35)
  #DictionaryCity.create(:name => 'Пятигорск', :dictionary_region_id => 35)
  #DictionaryCity.create(:name => 'Новопавловск', :dictionary_region_id => 35)
  #DictionaryCity.create(:name => 'Новоалександровск', :dictionary_region_id => 35)
  #DictionaryCity.create(:name => 'Нефтекумск', :dictionary_region_id => 35)
  #DictionaryCity.create(:name => 'Невинномысск', :dictionary_region_id => 35)
  #DictionaryCity.create(:name => 'Михайловск', :dictionary_region_id => 35)
  #DictionaryCity.create(:name => 'Минеральные Воды', :dictionary_region_id => 35)
  #DictionaryCity.create(:name => 'Лермонтов', :dictionary_region_id => 35)
  #DictionaryCity.create(:name => 'Кисловодск', :dictionary_region_id => 35)
  #DictionaryCity.create(:name => 'Ипатово', :dictionary_region_id => 35)
  #DictionaryCity.create(:name => 'Изобильный', :dictionary_region_id => 35)
  #DictionaryCity.create(:name => 'Зеленокумск', :dictionary_region_id => 35)
  #DictionaryCity.create(:name => 'Железноводск', :dictionary_region_id => 35)
  #DictionaryCity.create(:name => 'Ессентуки', :dictionary_region_id => 35)
  #DictionaryCity.create(:name => 'Георгиевск', :dictionary_region_id => 35)
  #DictionaryCity.create(:name => 'Будённовск', :dictionary_region_id => 35)
  #DictionaryCity.create(:name => 'Благодарный', :dictionary_region_id => 35)

  #DictionaryCity.create(:name => 'Шали', :dictionary_region_id => 36)
  #DictionaryCity.create(:name => 'Урус-Мартан', :dictionary_region_id => 36)
  #DictionaryCity.create(:name => 'Гудермес', :dictionary_region_id => 36)
  #DictionaryCity.create(:name => 'Грозный', :dictionary_region_id => 36)
  #DictionaryCity.create(:name => 'Аргун', :dictionary_region_id => 36)

  #DictionaryCity.create(:name => 'Моздок', :dictionary_region_id => 38)
  #DictionaryCity.create(:name => 'Дигора', :dictionary_region_id => 38)
  #DictionaryCity.create(:name => 'Владикавказ', :dictionary_region_id => 38)
  #DictionaryCity.create(:name => 'Беслан', :dictionary_region_id => 38)
  #DictionaryCity.create(:name => 'Ардон', :dictionary_region_id => 38)
  #DictionaryCity.create(:name => 'Алагир', :dictionary_region_id => 38)

  #DictionaryCity.create(:name => 'Черкесск', :dictionary_region_id => 37)
  #DictionaryCity.create(:name => 'Усть-Джегута', :dictionary_region_id => 37)
  #DictionaryCity.create(:name => 'Теберда', :dictionary_region_id => 37)
  #DictionaryCity.create(:name => 'Карачаевск', :dictionary_region_id => 37)

  #DictionaryCity.create(:name => 'Чегем', :dictionary_region_id => 39)
  #DictionaryCity.create(:name => 'Тырныауз', :dictionary_region_id => 39)
  #DictionaryCity.create(:name => 'Терек', :dictionary_region_id => 39)
  #DictionaryCity.create(:name => 'Прохладный', :dictionary_region_id => 39)
  #DictionaryCity.create(:name => 'Нарткала', :dictionary_region_id => 39)
  #DictionaryCity.create(:name => 'Нальчик', :dictionary_region_id => 39)
  #DictionaryCity.create(:name => 'Майский', :dictionary_region_id => 39)
  #DictionaryCity.create(:name => 'Баксан', :dictionary_region_id => 39)

  #DictionaryCity.create(:name => 'Назрань', :dictionary_region_id => 40)
  #DictionaryCity.create(:name => 'Малгобек', :dictionary_region_id => 40)
  #DictionaryCity.create(:name => 'Магас', :dictionary_region_id => 40)
  #DictionaryCity.create(:name => 'Карабулак', :dictionary_region_id => 40)

  #DictionaryCity.create(:name => 'Южно-Сухокумск', :dictionary_region_id => 29)
  #DictionaryCity.create(:name => 'Хасавюрт', :dictionary_region_id => 29)
  #DictionaryCity.create(:name => 'Махачкала', :dictionary_region_id => 29)
  #DictionaryCity.create(:name => 'Кизляр', :dictionary_region_id => 29)
  #DictionaryCity.create(:name => 'Кизилюрт', :dictionary_region_id => 29)
  #DictionaryCity.create(:name => 'Каспийск', :dictionary_region_id => 29)
  #DictionaryCity.create(:name => 'Избербаш', :dictionary_region_id => 29)
  #DictionaryCity.create(:name => 'Дербент', :dictionary_region_id => 29)
  #DictionaryCity.create(:name => 'Дагестанские Огни', :dictionary_region_id => 29)
  #DictionaryCity.create(:name => 'Буйнакск', :dictionary_region_id => 29)

  #DictionaryCity.create(:name => 'Шахты', :dictionary_region_id => 28)
  #DictionaryCity.create(:name => 'Цимлянск', :dictionary_region_id => 28)
  #DictionaryCity.create(:name => 'Таганрог', :dictionary_region_id => 28)
  #DictionaryCity.create(:name => 'Семикаракорск', :dictionary_region_id => 28)
  #DictionaryCity.create(:name => 'Сальск', :dictionary_region_id => 28)
  #DictionaryCity.create(:name => 'Ростов-на-Дону', :dictionary_region_id => 28)
  #DictionaryCity.create(:name => 'Пролетарск', :dictionary_region_id => 28)
  #DictionaryCity.create(:name => 'Новошахтинск', :dictionary_region_id => 28)
  #DictionaryCity.create(:name => 'Новочеркасск', :dictionary_region_id => 28)
  #DictionaryCity.create(:name => 'Морозовск', :dictionary_region_id => 28)
  #DictionaryCity.create(:name => 'Миллерово', :dictionary_region_id => 28)
  #DictionaryCity.create(:name => 'Красный Сулин', :dictionary_region_id => 28)
  #DictionaryCity.create(:name => 'Константиновск', :dictionary_region_id => 28)
  #DictionaryCity.create(:name => 'Каменск-Шахтинский', :dictionary_region_id => 28)
  #DictionaryCity.create(:name => 'Зерноград', :dictionary_region_id => 28)
  #DictionaryCity.create(:name => 'Зверево', :dictionary_region_id => 28)
  #DictionaryCity.create(:name => 'Донецк', :dictionary_region_id => 28)
  #DictionaryCity.create(:name => 'Гуково', :dictionary_region_id => 28)
  #DictionaryCity.create(:name => 'Волгодонск', :dictionary_region_id => 28)
  #DictionaryCity.create(:name => 'Белая Калитва', :dictionary_region_id => 28)
  #DictionaryCity.create(:name => 'Батайск', :dictionary_region_id => 28)
  #DictionaryCity.create(:name => 'Аксай', :dictionary_region_id => 28)
  #DictionaryCity.create(:name => 'Азов', :dictionary_region_id => 28)

  #DictionaryCity.create(:name => 'Фролово', :dictionary_region_id => 31)
  #DictionaryCity.create(:name => 'Урюпинск', :dictionary_region_id => 31)
  #DictionaryCity.create(:name => 'Суровикино', :dictionary_region_id => 31)
  #DictionaryCity.create(:name => 'Серафимович', :dictionary_region_id => 31)
  #DictionaryCity.create(:name => 'Петров Вал', :dictionary_region_id => 31)
  #DictionaryCity.create(:name => 'Палласовка', :dictionary_region_id => 31)
  #DictionaryCity.create(:name => 'Новоаннинский', :dictionary_region_id => 31)
  #DictionaryCity.create(:name => 'Николаевск', :dictionary_region_id => 31)
  #DictionaryCity.create(:name => 'Михайловка', :dictionary_region_id => 31)
  #DictionaryCity.create(:name => 'Ленинск', :dictionary_region_id => 31)
  #DictionaryCity.create(:name => 'Краснослободск', :dictionary_region_id => 31)
  #DictionaryCity.create(:name => 'Котово', :dictionary_region_id => 31)
  #DictionaryCity.create(:name => 'Котельниково', :dictionary_region_id => 31)
  #DictionaryCity.create(:name => 'Камышин', :dictionary_region_id => 31)
  #DictionaryCity.create(:name => 'Калач-на-Дону', :dictionary_region_id => 31)
  #DictionaryCity.create(:name => 'Жирновск', :dictionary_region_id => 31)
  #DictionaryCity.create(:name => 'Дубовка', :dictionary_region_id => 31)
  #DictionaryCity.create(:name => 'Волжский', :dictionary_region_id => 31)
  #DictionaryCity.create(:name => 'Волгоград', :dictionary_region_id => 31)

  #DictionaryCity.create(:name => 'Харабали', :dictionary_region_id => 30)
  #DictionaryCity.create(:name => 'Нариманов', :dictionary_region_id => 30)
  #DictionaryCity.create(:name => 'Камызяк', :dictionary_region_id => 30)
  #DictionaryCity.create(:name => 'Знаменск', :dictionary_region_id => 30)
  #DictionaryCity.create(:name => 'Ахтубинск', :dictionary_region_id => 30)
  #DictionaryCity.create(:name => 'Астрахань', :dictionary_region_id => 30)

  #DictionaryCity.create(:name => 'Хадыженск', :dictionary_region_id => 32)
  #DictionaryCity.create(:name => 'Усть-Лабинск', :dictionary_region_id => 32)
  #DictionaryCity.create(:name => 'Туапсе', :dictionary_region_id => 32)
  #DictionaryCity.create(:name => 'Тихорецк', :dictionary_region_id => 32)
  #DictionaryCity.create(:name => 'Тимашевск', :dictionary_region_id => 32)
  #DictionaryCity.create(:name => 'Темрюк', :dictionary_region_id => 32)
  #DictionaryCity.create(:name => 'Сочи', :dictionary_region_id => 32)
  #DictionaryCity.create(:name => 'Славянск-на-Кубани', :dictionary_region_id => 32)
  #DictionaryCity.create(:name => 'Приморско-Ахтарск', :dictionary_region_id => 32)
  #DictionaryCity.create(:name => 'Новороссийск', :dictionary_region_id => 32)
  #DictionaryCity.create(:name => 'Новокубанск', :dictionary_region_id => 32)
  #DictionaryCity.create(:name => 'Лабинск', :dictionary_region_id => 32)
  #DictionaryCity.create(:name => 'Курганинск', :dictionary_region_id => 32)
  #DictionaryCity.create(:name => 'Крымск', :dictionary_region_id => 32)
  #DictionaryCity.create(:name => 'Кропоткин', :dictionary_region_id => 32)
  #DictionaryCity.create(:name => 'Краснодар', :dictionary_region_id => 32)
  #DictionaryCity.create(:name => 'Кореновск', :dictionary_region_id => 32)
  #DictionaryCity.create(:name => 'Ейск', :dictionary_region_id => 32)
  #DictionaryCity.create(:name => 'Гулькевичи', :dictionary_region_id => 32)
  #DictionaryCity.create(:name => 'Горячий Ключ', :dictionary_region_id => 32)
  #DictionaryCity.create(:name => 'Геленджик', :dictionary_region_id => 32)
  #DictionaryCity.create(:name => 'Белореченск', :dictionary_region_id => 32)
  #DictionaryCity.create(:name => 'Армавир', :dictionary_region_id => 32)
  #DictionaryCity.create(:name => 'Апшеронск', :dictionary_region_id => 32)
  #DictionaryCity.create(:name => 'Анапа', :dictionary_region_id => 32)
  #DictionaryCity.create(:name => 'Абинск', :dictionary_region_id => 32)

  #DictionaryCity.create(:name => 'Элиста', :dictionary_region_id => 33)
  #DictionaryCity.create(:name => 'Лагань', :dictionary_region_id => 33)
  #DictionaryCity.create(:name => 'Городовиковск', :dictionary_region_id => 33)

  #DictionaryCity.create(:name => 'Майкоп', :dictionary_region_id => 34)
  #DictionaryCity.create(:name => 'Адыгейск', :dictionary_region_id => 34)

  #DictionaryCity.create(:name => 'Себеж', :dictionary_region_id => 27)
  #DictionaryCity.create(:name => 'Пыталово', :dictionary_region_id => 27)
  #DictionaryCity.create(:name => 'Пустошка', :dictionary_region_id => 27)
  #DictionaryCity.create(:name => 'Псков', :dictionary_region_id => 27)
  #DictionaryCity.create(:name => 'Порхов', :dictionary_region_id => 27)
  #DictionaryCity.create(:name => 'Печоры', :dictionary_region_id => 27)
  #DictionaryCity.create(:name => 'Остров', :dictionary_region_id => 27)
  #DictionaryCity.create(:name => 'Опочка', :dictionary_region_id => 27)
  #DictionaryCity.create(:name => 'Новосокольники', :dictionary_region_id => 27)
  #DictionaryCity.create(:name => 'Новоржев', :dictionary_region_id => 27)
  #DictionaryCity.create(:name => 'Невель', :dictionary_region_id => 27)
  #DictionaryCity.create(:name => 'Дно', :dictionary_region_id => 27)
  #DictionaryCity.create(:name => 'Гдов', :dictionary_region_id => 27)
  #DictionaryCity.create(:name => 'Великие Луки', :dictionary_region_id => 27)

  #DictionaryCity.create(:name => 'Чудово', :dictionary_region_id => 18)
  #DictionaryCity.create(:name => 'Холм', :dictionary_region_id => 18)
  #DictionaryCity.create(:name => 'Старая Русса', :dictionary_region_id => 18)
  #DictionaryCity.create(:name => 'Сольцы', :dictionary_region_id => 18)
  #DictionaryCity.create(:name => 'Пестово', :dictionary_region_id => 18)
  #DictionaryCity.create(:name => 'Окуловка', :dictionary_region_id => 18)
  #DictionaryCity.create(:name => 'Малая Вишера', :dictionary_region_id => 18)
  #DictionaryCity.create(:name => 'Великий Новгород', :dictionary_region_id => 18)
  #DictionaryCity.create(:name => 'Валдай', :dictionary_region_id => 18)
  #DictionaryCity.create(:name => 'Боровичи', :dictionary_region_id => 18)

  #DictionaryCity.create(:name => 'Снежногорск', :dictionary_region_id => 19)
  #DictionaryCity.create(:name => 'Североморск', :dictionary_region_id => 19)
  #DictionaryCity.create(:name => 'Полярный', :dictionary_region_id => 19)
  #DictionaryCity.create(:name => 'Полярные Зори', :dictionary_region_id => 19)
  #DictionaryCity.create(:name => 'Островной', :dictionary_region_id => 19)
  #DictionaryCity.create(:name => 'Оленегорск', :dictionary_region_id => 19)
  #DictionaryCity.create(:name => 'Мурманск', :dictionary_region_id => 19)
  #DictionaryCity.create(:name => 'Мончегорск', :dictionary_region_id => 19)
  #DictionaryCity.create(:name => 'Кола', :dictionary_region_id => 19)
  #DictionaryCity.create(:name => 'Ковдор', :dictionary_region_id => 19)
  #DictionaryCity.create(:name => 'Кандалакша', :dictionary_region_id => 19)
  #DictionaryCity.create(:name => 'Заполярный', :dictionary_region_id => 19)
  #DictionaryCity.create(:name => 'Заозёрск', :dictionary_region_id => 19)
  #DictionaryCity.create(:name => 'Гаджиево', :dictionary_region_id => 19)
  #DictionaryCity.create(:name => 'Апатиты', :dictionary_region_id => 19)
  #DictionaryCity.create(:name => 'Кировск', :dictionary_region_id => 19)

  #DictionaryCity.create(:name => 'Шлиссельбург', :dictionary_region_id => 20)
  #DictionaryCity.create(:name => 'Тосно', :dictionary_region_id => 20)
  #DictionaryCity.create(:name => 'Тихвин', :dictionary_region_id => 20)
  #DictionaryCity.create(:name => 'Сясьстрой', :dictionary_region_id => 20)
  #DictionaryCity.create(:name => 'Сосновый Бор', :dictionary_region_id => 20)
  #DictionaryCity.create(:name => 'Сланцы', :dictionary_region_id => 20)
  #DictionaryCity.create(:name => 'Сертолово', :dictionary_region_id => 20)
  #DictionaryCity.create(:name => 'Светогорск', :dictionary_region_id => 20)
  #DictionaryCity.create(:name => 'Санкт-Петербург', :dictionary_region_id => 20)
  #DictionaryCity.create(:name => 'Приозерск', :dictionary_region_id => 20)
  #DictionaryCity.create(:name => 'Приморск', :dictionary_region_id => 20)
  #DictionaryCity.create(:name => 'Подпорожье', :dictionary_region_id => 20)
  #DictionaryCity.create(:name => 'Пикалёво', :dictionary_region_id => 20)
  #DictionaryCity.create(:name => 'Отрадное', :dictionary_region_id => 20)
  #DictionaryCity.create(:name => 'Новая Ладога', :dictionary_region_id => 20)
  #DictionaryCity.create(:name => 'Никольское', :dictionary_region_id => 20)
  #DictionaryCity.create(:name => 'Любань', :dictionary_region_id => 20)
  #DictionaryCity.create(:name => 'Луга', :dictionary_region_id => 20)
  #DictionaryCity.create(:name => 'Лодейное Поле', :dictionary_region_id => 20)
  #DictionaryCity.create(:name => 'Коммунар', :dictionary_region_id => 20)
  #DictionaryCity.create(:name => 'Кировск', :dictionary_region_id => 20)
  #DictionaryCity.create(:name => 'Кириши', :dictionary_region_id => 20)
  #DictionaryCity.create(:name => 'Кингисепп', :dictionary_region_id => 20)
  #DictionaryCity.create(:name => 'Каменногорск', :dictionary_region_id => 20)
  #DictionaryCity.create(:name => 'Ивангород', :dictionary_region_id => 20)
  #DictionaryCity.create(:name => 'Гатчина', :dictionary_region_id => 20)
  #DictionaryCity.create(:name => 'Высоцк', :dictionary_region_id => 20)
  #DictionaryCity.create(:name => 'Выборг', :dictionary_region_id => 20)
  #DictionaryCity.create(:name => 'Всеволожск', :dictionary_region_id => 20)
  #DictionaryCity.create(:name => 'Волхов', :dictionary_region_id => 20)
  #DictionaryCity.create(:name => 'Волосово', :dictionary_region_id => 20)
  #DictionaryCity.create(:name => 'Бокситогорск', :dictionary_region_id => 20)

  #DictionaryCity.create(:name => 'Черняховск', :dictionary_region_id => 21)
  #DictionaryCity.create(:name => 'Славск', :dictionary_region_id => 21)
  #DictionaryCity.create(:name => 'Светлый', :dictionary_region_id => 21)
  #DictionaryCity.create(:name => 'Светлогорск', :dictionary_region_id => 21)
  #DictionaryCity.create(:name => 'Правдинск', :dictionary_region_id => 21)
  #DictionaryCity.create(:name => 'Полесск', :dictionary_region_id => 21)
  #DictionaryCity.create(:name => 'Пионерский', :dictionary_region_id => 21)
  #DictionaryCity.create(:name => 'Озёрск', :dictionary_region_id => 21)
  #DictionaryCity.create(:name => 'Нестеров', :dictionary_region_id => 21)
  #DictionaryCity.create(:name => 'Неман', :dictionary_region_id => 21)
  #DictionaryCity.create(:name => 'Мамоново', :dictionary_region_id => 21)
  #DictionaryCity.create(:name => 'Ладушкин', :dictionary_region_id => 21)
  #DictionaryCity.create(:name => 'Калининград', :dictionary_region_id => 21)
  #DictionaryCity.create(:name => 'Зеленоградск', :dictionary_region_id => 21)
  #DictionaryCity.create(:name => 'Гусев', :dictionary_region_id => 21)
  #DictionaryCity.create(:name => 'Гурьевск', :dictionary_region_id => 21)
  #DictionaryCity.create(:name => 'Гвардейск', :dictionary_region_id => 21)
  #DictionaryCity.create(:name => 'Балтийск', :dictionary_region_id => 21)
  #DictionaryCity.create(:name => 'Багратионовск', :dictionary_region_id => 21)
  #DictionaryCity.create(:name => 'Советск', :dictionary_region_id => 21)
  #DictionaryCity.create(:name => 'Приморск', :dictionary_region_id => 21)
  #DictionaryCity.create(:name => 'Краснознаменск', :dictionary_region_id => 21)

  #DictionaryCity.create(:name => 'Череповец', :dictionary_region_id => 22)
  #DictionaryCity.create(:name => 'Харовск', :dictionary_region_id => 22)
  #DictionaryCity.create(:name => 'Устюжна', :dictionary_region_id => 22)
  #DictionaryCity.create(:name => 'Тотьма', :dictionary_region_id => 22)
  #DictionaryCity.create(:name => 'Сокол', :dictionary_region_id => 22)
  #DictionaryCity.create(:name => 'Никольск', :dictionary_region_id => 22)
  #DictionaryCity.create(:name => 'Красавино', :dictionary_region_id => 22)
  #DictionaryCity.create(:name => 'Кириллов', :dictionary_region_id => 22)
  #DictionaryCity.create(:name => 'Кадников', :dictionary_region_id => 22)
  #DictionaryCity.create(:name => 'Грязовец', :dictionary_region_id => 22)
  #DictionaryCity.create(:name => 'Вытегра', :dictionary_region_id => 22)
  #DictionaryCity.create(:name => 'Вологда', :dictionary_region_id => 22)
  #DictionaryCity.create(:name => 'Великий Устюг', :dictionary_region_id => 22)
  #DictionaryCity.create(:name => 'Белозерск', :dictionary_region_id => 22)
  #DictionaryCity.create(:name => 'Бабаево', :dictionary_region_id => 22)

  #DictionaryCity.create(:name => 'Нарьян-Мар', :dictionary_region_id => 23)

  #DictionaryCity.create(:name => 'Шенкурск', :dictionary_region_id => 24)
  #DictionaryCity.create(:name => 'Сольвычегодск', :dictionary_region_id => 24)
  #DictionaryCity.create(:name => 'Северодвинск', :dictionary_region_id => 24)
  #DictionaryCity.create(:name => 'Онега', :dictionary_region_id => 24)
  #DictionaryCity.create(:name => 'Няндома', :dictionary_region_id => 24)
  #DictionaryCity.create(:name => 'Новодвинск', :dictionary_region_id => 24)
  #DictionaryCity.create(:name => 'Мирный', :dictionary_region_id => 24)
  #DictionaryCity.create(:name => 'Мезень', :dictionary_region_id => 24)
  #DictionaryCity.create(:name => 'Котлас', :dictionary_region_id => 24)
  #DictionaryCity.create(:name => 'Коряжма', :dictionary_region_id => 24)
  #DictionaryCity.create(:name => 'Каргополь', :dictionary_region_id => 24)
  #DictionaryCity.create(:name => 'Вельск', :dictionary_region_id => 24)
  #DictionaryCity.create(:name => 'Архангельск', :dictionary_region_id => 24)

  #DictionaryCity.create(:name => 'Ухта', :dictionary_region_id => 25)
  #DictionaryCity.create(:name => 'Усинск', :dictionary_region_id => 25)
  #DictionaryCity.create(:name => 'Сыктывкар', :dictionary_region_id => 25)
  #DictionaryCity.create(:name => 'Сосногорск', :dictionary_region_id => 25)
  #DictionaryCity.create(:name => 'Печора', :dictionary_region_id => 25)
  #DictionaryCity.create(:name => 'Микунь', :dictionary_region_id => 25)
  #DictionaryCity.create(:name => 'Инта', :dictionary_region_id => 25)
  #DictionaryCity.create(:name => 'Емва', :dictionary_region_id => 25)
  #DictionaryCity.create(:name => 'Вуктыл', :dictionary_region_id => 25)
  #DictionaryCity.create(:name => 'Воркута', :dictionary_region_id => 25)

  #DictionaryCity.create(:name => 'Суоярви', :dictionary_region_id => 26)
  #DictionaryCity.create(:name => 'Сортавала', :dictionary_region_id => 26)
  #DictionaryCity.create(:name => 'Сегежа', :dictionary_region_id => 26)
  #DictionaryCity.create(:name => 'Пудож', :dictionary_region_id => 26)
  #DictionaryCity.create(:name => 'Питкяранта', :dictionary_region_id => 26)
  #DictionaryCity.create(:name => 'Петрозаводск', :dictionary_region_id => 26)
  #DictionaryCity.create(:name => 'Олонец', :dictionary_region_id => 26)
  #DictionaryCity.create(:name => 'Медвежьегорск', :dictionary_region_id => 26)
  #DictionaryCity.create(:name => 'Лахденпохья', :dictionary_region_id => 26)
  #DictionaryCity.create(:name => 'Костомукша', :dictionary_region_id => 26)
  #DictionaryCity.create(:name => 'Кондопога', :dictionary_region_id => 26)
  #DictionaryCity.create(:name => 'Кемь', :dictionary_region_id => 26)
  #DictionaryCity.create(:name => 'Беломорск', :dictionary_region_id => 26)

  #DictionaryCity.create(:name => 'Ярославль', :dictionary_region_id => 1)
  #DictionaryCity.create(:name => 'Углич', :dictionary_region_id => 1)
  #DictionaryCity.create(:name => 'Тутаев', :dictionary_region_id => 1)
  #DictionaryCity.create(:name => 'Рыбинск', :dictionary_region_id => 1)
  #DictionaryCity.create(:name => 'Ростов', :dictionary_region_id => 1)
  #DictionaryCity.create(:name => 'Пошехонье', :dictionary_region_id => 1)
  #DictionaryCity.create(:name => 'Переславль-Залесский', :dictionary_region_id => 1)
  #DictionaryCity.create(:name => 'Мышкин', :dictionary_region_id => 1)
  #DictionaryCity.create(:name => 'Любим', :dictionary_region_id => 1)
  #DictionaryCity.create(:name => 'Данилов', :dictionary_region_id => 1)
  #DictionaryCity.create(:name => 'Гаврилов-Ям', :dictionary_region_id => 1)

  #DictionaryCity.create(:name => 'Ясногорск', :dictionary_region_id => 2)
  #DictionaryCity.create(:name => 'Щёкино', :dictionary_region_id => 2)
  #DictionaryCity.create(:name => 'Чекалин', :dictionary_region_id => 2)
  #DictionaryCity.create(:name => 'Узловая', :dictionary_region_id => 2)
  #DictionaryCity.create(:name => 'Тула', :dictionary_region_id => 2)
  #DictionaryCity.create(:name => 'Суворов', :dictionary_region_id => 2)
  #DictionaryCity.create(:name => 'Советск', :dictionary_region_id => 2)
  #DictionaryCity.create(:name => 'Плавск', :dictionary_region_id => 2)
  #DictionaryCity.create(:name => 'Новомосковск', :dictionary_region_id => 2)
  #DictionaryCity.create(:name => 'Липки', :dictionary_region_id => 2)
  #DictionaryCity.create(:name => 'Киреевск', :dictionary_region_id => 2)
  #DictionaryCity.create(:name => 'Кимовск', :dictionary_region_id => 2)
  #DictionaryCity.create(:name => 'Ефремов', :dictionary_region_id => 2)
  #DictionaryCity.create(:name => 'Донской', :dictionary_region_id => 2)
  #DictionaryCity.create(:name => 'Венёв', :dictionary_region_id => 2)
  #DictionaryCity.create(:name => 'Болохово', :dictionary_region_id => 2)
  #DictionaryCity.create(:name => 'Богородицк', :dictionary_region_id => 2)
  #DictionaryCity.create(:name => 'Белёв', :dictionary_region_id => 2)
  #DictionaryCity.create(:name => 'Алексин', :dictionary_region_id => 2)

  #DictionaryCity.create(:name => 'Удомля', :dictionary_region_id => 3)
  #DictionaryCity.create(:name => 'Торопец', :dictionary_region_id => 3)
  #DictionaryCity.create(:name => 'Торжок', :dictionary_region_id => 3)
  #DictionaryCity.create(:name => 'Тверь', :dictionary_region_id => 3)
  #DictionaryCity.create(:name => 'Старица', :dictionary_region_id => 3)
  #DictionaryCity.create(:name => 'Ржев', :dictionary_region_id => 3)
  #DictionaryCity.create(:name => 'Осташков', :dictionary_region_id => 3)
  #DictionaryCity.create(:name => 'Нелидово', :dictionary_region_id => 3)
  #DictionaryCity.create(:name => 'Лихославль', :dictionary_region_id => 3)
  #DictionaryCity.create(:name => 'Кувшиново', :dictionary_region_id => 3)
  #DictionaryCity.create(:name => 'Красный Холм', :dictionary_region_id => 3)
  #DictionaryCity.create(:name => 'Конаково', :dictionary_region_id => 3)
  #DictionaryCity.create(:name => 'Кимры', :dictionary_region_id => 3)
  #DictionaryCity.create(:name => 'Кашин', :dictionary_region_id => 3)
  #DictionaryCity.create(:name => 'Калязин', :dictionary_region_id => 3)
  #DictionaryCity.create(:name => 'Зубцов', :dictionary_region_id => 3)
  #DictionaryCity.create(:name => 'Западная Двина', :dictionary_region_id => 3)
  #DictionaryCity.create(:name => 'Вышний Волочёк', :dictionary_region_id => 3)
  #DictionaryCity.create(:name => 'Весьегонск', :dictionary_region_id => 3)
  #DictionaryCity.create(:name => 'Бологое', :dictionary_region_id => 3)
  #DictionaryCity.create(:name => 'Белый', :dictionary_region_id => 3)
  #DictionaryCity.create(:name => 'Бежецк', :dictionary_region_id => 3)
  #DictionaryCity.create(:name => 'Андреаполь', :dictionary_region_id => 3)

  #DictionaryCity.create(:name => 'Уварово', :dictionary_region_id => 4)
  #DictionaryCity.create(:name => 'Тамбов', :dictionary_region_id => 4)
  #DictionaryCity.create(:name => 'Рассказово', :dictionary_region_id => 4)
  #DictionaryCity.create(:name => 'Моршанск', :dictionary_region_id => 4)
  #DictionaryCity.create(:name => 'Мичуринск', :dictionary_region_id => 4)
  #DictionaryCity.create(:name => 'Котовск', :dictionary_region_id => 4)
  #DictionaryCity.create(:name => 'Кирсанов', :dictionary_region_id => 4)
  #DictionaryCity.create(:name => 'Жердевка', :dictionary_region_id => 4)

  #DictionaryCity.create(:name => 'Ярцево', :dictionary_region_id => 5)
  #DictionaryCity.create(:name => 'Сычевка', :dictionary_region_id => 5)
  #DictionaryCity.create(:name => 'Смоленск', :dictionary_region_id => 5)
  #DictionaryCity.create(:name => 'Сафоново', :dictionary_region_id => 5)
  #DictionaryCity.create(:name => 'Рудня', :dictionary_region_id => 5)
  #DictionaryCity.create(:name => 'Рославль', :dictionary_region_id => 5)
  #DictionaryCity.create(:name => 'Починок', :dictionary_region_id => 5)
  #DictionaryCity.create(:name => 'Ельня', :dictionary_region_id => 5)
  #DictionaryCity.create(:name => 'Духовщина', :dictionary_region_id => 5)
  #DictionaryCity.create(:name => 'Дорогобуж', :dictionary_region_id => 5)
  #DictionaryCity.create(:name => 'Десногорск', :dictionary_region_id => 5)
  #DictionaryCity.create(:name => 'Демидов', :dictionary_region_id => 5)
  #DictionaryCity.create(:name => 'Гагарин', :dictionary_region_id => 5)
  #DictionaryCity.create(:name => 'Вязьма', :dictionary_region_id => 5)
  #DictionaryCity.create(:name => 'Велиж', :dictionary_region_id => 5)

  #DictionaryCity.create(:name => 'Шацк', :dictionary_region_id => 6)
  #DictionaryCity.create(:name => 'Спасск-Рязанский', :dictionary_region_id => 6)
  #DictionaryCity.create(:name => 'Спас-Клепики', :dictionary_region_id => 6)
  #DictionaryCity.create(:name => 'Скопин', :dictionary_region_id => 6)
  #DictionaryCity.create(:name => 'Сасово', :dictionary_region_id => 6)
  #DictionaryCity.create(:name => 'Рязань', :dictionary_region_id => 6)
  #DictionaryCity.create(:name => 'Ряжск', :dictionary_region_id => 6)
  #DictionaryCity.create(:name => 'Рыбное', :dictionary_region_id => 6)
  #DictionaryCity.create(:name => 'Новомичуринск', :dictionary_region_id => 6)
  #DictionaryCity.create(:name => 'Михайлов', :dictionary_region_id => 6)
  #DictionaryCity.create(:name => 'Кораблино', :dictionary_region_id => 6)
  #DictionaryCity.create(:name => 'Касимов', :dictionary_region_id => 6)

  #DictionaryCity.create(:name => 'Орёл', :dictionary_region_id => 7)
  #DictionaryCity.create(:name => 'Новосиль', :dictionary_region_id => 7)
  #DictionaryCity.create(:name => 'Мценск', :dictionary_region_id => 7)
  #DictionaryCity.create(:name => 'Малоархангельск', :dictionary_region_id => 7)
  #DictionaryCity.create(:name => 'Ливны', :dictionary_region_id => 7)
  #DictionaryCity.create(:name => 'Дмитровск', :dictionary_region_id => 7);
  #DictionaryCity.create(:name => 'Болхов', :dictionary_region_id => 7)

  #DictionaryCity.create(:name => 'Яхрома', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Юбилейный', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Электроугли', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Электросталь', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Электрогорск', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Щербинка', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Щёлково', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Шатура', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Чехов', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Черноголовка', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Хотьково', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Химки', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Фрязино', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Троицк', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Талдом', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Ступино', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Солнечногорск', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Серпухов', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Сергиев Посад', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Руза', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Рошаль', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Реутов', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Раменское', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Пущино', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Пушкино', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Протвино', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Подольск', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Пересвет', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Павловский Посад', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Орехово-Зуево', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Озёры', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Ожерелье', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Одинцово', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Ногинск', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Наро-Фоминск', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Мытищи', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Москва', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Можайск', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Люберцы', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Лыткарино', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Луховицы', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Лосино-Петровский', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Лобня', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Ликино-Дулёво', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Куровское', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Краснознаменск', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Краснозаводск', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Красногорск', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Красноармейск', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Королёв', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Коломна', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Клин', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Климовск', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Кашира', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Истра', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Ивантеевка', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Звенигород', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Зарайск', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Жуковский', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Железнодорожный', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Егорьевск', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Дубна', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Дрезна', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Домодедово', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Долгопрудный', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Дмитров', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Дзержинский', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Дедовск', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Высоковск', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Воскресенск', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Волоколамск', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Видное', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Верея', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Бронницы', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Балашиха', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Апрелевка', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Котельники', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Московский', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Старая Купавна', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Голицино', :dictionary_region_id => 8)
  #DictionaryCity.create(:name => 'Кубинка', :dictionary_region_id => 8)

  #DictionaryCity.create(:name => 'Чаплыгин', :dictionary_region_id => 10)
  #DictionaryCity.create(:name => 'Усмань', :dictionary_region_id => 10)
  #DictionaryCity.create(:name => 'Липецк', :dictionary_region_id => 10)
  #DictionaryCity.create(:name => 'Лебедянь', :dictionary_region_id => 10)
  #DictionaryCity.create(:name => 'Задонск', :dictionary_region_id => 10)
  #DictionaryCity.create(:name => 'Елец', :dictionary_region_id => 10)
  #DictionaryCity.create(:name => 'Данков', :dictionary_region_id => 10)
  #DictionaryCity.create(:name => 'Грязи', :dictionary_region_id => 10)

  #DictionaryCity.create(:name => 'Щигры', :dictionary_region_id => 9)
  #DictionaryCity.create(:name => 'Фатеж', :dictionary_region_id => 9)
  #DictionaryCity.create(:name => 'Суджа', :dictionary_region_id => 9)
  #DictionaryCity.create(:name => 'Рыльск', :dictionary_region_id => 9)
  #DictionaryCity.create(:name => 'Обоянь', :dictionary_region_id => 9)
  #DictionaryCity.create(:name => 'Льгов', :dictionary_region_id => 9)
  #DictionaryCity.create(:name => 'Курчатов', :dictionary_region_id => 9)
  #DictionaryCity.create(:name => 'Курск', :dictionary_region_id => 9)
  #DictionaryCity.create(:name => 'Железногорск', :dictionary_region_id => 9)
  #DictionaryCity.create(:name => 'Дмитриев-Льговский', :dictionary_region_id => 9)

  #DictionaryCity.create(:name => 'Шарья', :dictionary_region_id => 11)
  #DictionaryCity.create(:name => 'Чухлома', :dictionary_region_id => 11)
  #DictionaryCity.create(:name => 'Солигалич', :dictionary_region_id => 11)
  #DictionaryCity.create(:name => 'Нея', :dictionary_region_id => 11)
  #DictionaryCity.create(:name => 'Нерехта', :dictionary_region_id => 11)
  #DictionaryCity.create(:name => 'Мантурово', :dictionary_region_id => 11)
  #DictionaryCity.create(:name => 'Макарьев', :dictionary_region_id => 11)
  #DictionaryCity.create(:name => 'Кострома', :dictionary_region_id => 11)
  #DictionaryCity.create(:name => 'Кологрив', :dictionary_region_id => 11)
  #DictionaryCity.create(:name => 'Галич', :dictionary_region_id => 11)
  #DictionaryCity.create(:name => 'Волгореченск', :dictionary_region_id => 11)
  #DictionaryCity.create(:name => 'Буй', :dictionary_region_id => 11)

  #DictionaryCity.create(:name => 'Алапаевск', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Арамиль', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Артёмовский', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Асбест', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Берёзовский', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Богданович', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Верхний Тагил', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Верхняя Пышма', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Верхняя Салда', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Верхняя Тура', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Верхотурье', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Волчанск', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Дегтярск', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Екатеринбург', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Ивдель', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Ирбит', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Каменск-Уральский', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Камышлов', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Карпинск', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Качканар', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Кировград', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Краснотурьинск', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Красноуральск', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Красноуфимск', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Кушва', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Лесной', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Невьянск', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Нижние Серги', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Нижний Тагил', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Нижняя Салда', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Нижняя Тура', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Новая Ляля', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Новоуральск', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Первоуральск', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Полевской', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Ревда', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Реж', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Североуральск', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Серов', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Среднеуральск', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Сухой Лог', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Сысерть', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Тавда', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Талица', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Туринск', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Верхний Тагил', :dictionary_region_id => 59)
  #DictionaryCity.create(:name => 'Михайловск', :dictionary_region_id => 59)

  #DictionaryCity.create(:name => 'Заводоуковск', :dictionary_region_id => 58)
  #DictionaryCity.create(:name => 'Ишим', :dictionary_region_id => 58)
  #DictionaryCity.create(:name => 'Тобольск', :dictionary_region_id => 58)
  #DictionaryCity.create(:name => 'Тюмень', :dictionary_region_id => 58)
  #DictionaryCity.create(:name => 'Ялуторовск', :dictionary_region_id => 58)

  #DictionaryCity.create(:name => 'Белоярский', :dictionary_region_id => 57)
  #DictionaryCity.create(:name => 'Когалым', :dictionary_region_id => 57)
  #DictionaryCity.create(:name => 'Лангепас', :dictionary_region_id => 57)
  #DictionaryCity.create(:name => 'Лянтор', :dictionary_region_id => 57)
  #DictionaryCity.create(:name => 'Мегион', :dictionary_region_id => 57)
  #DictionaryCity.create(:name => 'Нефтеюганск', :dictionary_region_id => 57)
  #DictionaryCity.create(:name => 'Нижневартовск', :dictionary_region_id => 57)
  #DictionaryCity.create(:name => 'Нягань', :dictionary_region_id => 57)
  #DictionaryCity.create(:name => 'Покачи', :dictionary_region_id => 57)
  #DictionaryCity.create(:name => 'Пыть-Ях', :dictionary_region_id => 57)
  #DictionaryCity.create(:name => 'Советский', :dictionary_region_id => 57)
  #DictionaryCity.create(:name => 'Сургут', :dictionary_region_id => 57)
  #DictionaryCity.create(:name => 'Урай', :dictionary_region_id => 57)
  #DictionaryCity.create(:name => 'Ханты-Мансийск', :dictionary_region_id => 57)
  #DictionaryCity.create(:name => 'Югорск', :dictionary_region_id => 57)
  #DictionaryCity.create(:name => 'Радужный', :dictionary_region_id => 57)

  #DictionaryCity.create(:name => 'Губкинский', :dictionary_region_id => 55)
  #DictionaryCity.create(:name => 'Лабытнанги', :dictionary_region_id => 55)
  #DictionaryCity.create(:name => 'Муравленко', :dictionary_region_id => 55)
  #DictionaryCity.create(:name => 'Надым', :dictionary_region_id => 55)
  #DictionaryCity.create(:name => 'Новый Уренгой', :dictionary_region_id => 55)
  #DictionaryCity.create(:name => 'Ноябрьск', :dictionary_region_id => 55)
  #DictionaryCity.create(:name => 'Салехард', :dictionary_region_id => 55)

  #DictionaryCity.create(:name => 'Аша', :dictionary_region_id => 56)
  #DictionaryCity.create(:name => 'Бакал', :dictionary_region_id => 56)
  #DictionaryCity.create(:name => 'Верхнеуральск', :dictionary_region_id => 56)
  #DictionaryCity.create(:name => 'Верхний Уфалей', :dictionary_region_id => 56)
  #DictionaryCity.create(:name => 'Еманжелинск', :dictionary_region_id => 56)
  #DictionaryCity.create(:name => 'Златоуст', :dictionary_region_id => 56)
  #DictionaryCity.create(:name => 'Карабаш', :dictionary_region_id => 56)
  #DictionaryCity.create(:name => 'Карталы', :dictionary_region_id => 56)
  #DictionaryCity.create(:name => 'Касли', :dictionary_region_id => 56)
  #DictionaryCity.create(:name => 'Катав-Ивановск', :dictionary_region_id => 56)
  #DictionaryCity.create(:name => 'Копейск', :dictionary_region_id => 56)
  #DictionaryCity.create(:name => 'Коркино', :dictionary_region_id => 56)
  #DictionaryCity.create(:name => 'Куса', :dictionary_region_id => 56)
  #DictionaryCity.create(:name => 'Кыштым', :dictionary_region_id => 56)
  #DictionaryCity.create(:name => 'Магнитогорск', :dictionary_region_id => 56)
  #DictionaryCity.create(:name => 'Миасс', :dictionary_region_id => 56)
  #DictionaryCity.create(:name => 'Миньяр', :dictionary_region_id => 56)
  #DictionaryCity.create(:name => 'Нязепетровск', :dictionary_region_id => 56)
  #DictionaryCity.create(:name => 'Пласт', :dictionary_region_id => 56)
  #DictionaryCity.create(:name => 'Сатка', :dictionary_region_id => 56)
  #DictionaryCity.create(:name => 'Сим', :dictionary_region_id => 56)
  #DictionaryCity.create(:name => 'Снежинск', :dictionary_region_id => 56)
  #DictionaryCity.create(:name => 'Трехгорный', :dictionary_region_id => 56)
  #DictionaryCity.create(:name => 'Усть-Катав', :dictionary_region_id => 56)
  #DictionaryCity.create(:name => 'Чебаркуль', :dictionary_region_id => 56)
  #DictionaryCity.create(:name => 'Челябинск', :dictionary_region_id => 56)
  #DictionaryCity.create(:name => 'Южноуральск', :dictionary_region_id => 56)
  #DictionaryCity.create(:name => 'Юрюзань', :dictionary_region_id => 56)
  #DictionaryCity.create(:name => 'Троицк', :dictionary_region_id => 56)

  #DictionaryCity.create(:name => 'Горно-Алтайск', :dictionary_region_id => 69)

  #DictionaryCity.create(:name => 'Бабушкин', :dictionary_region_id => 70)
  #DictionaryCity.create(:name => 'Гусиноозёрск', :dictionary_region_id => 70)
  #DictionaryCity.create(:name => 'Закаменск', :dictionary_region_id => 70)
  #DictionaryCity.create(:name => 'Кяхта', :dictionary_region_id => 70)
  #DictionaryCity.create(:name => 'Северобайкальск', :dictionary_region_id => 70)
  #DictionaryCity.create(:name => 'Улан-Удэ', :dictionary_region_id => 70)

  #DictionaryCity.create(:name => 'Ак-Довурак', :dictionary_region_id => 71)
  #DictionaryCity.create(:name => 'Кызыл', :dictionary_region_id => 71)
  #DictionaryCity.create(:name => 'Туран', :dictionary_region_id => 71)
  #DictionaryCity.create(:name => 'Чадан', :dictionary_region_id => 71)
  #DictionaryCity.create(:name => 'Шагонар', :dictionary_region_id =>71 )

  #DictionaryCity.create(:name => 'Абаза', :dictionary_region_id => 68)
  #DictionaryCity.create(:name => 'Абакан', :dictionary_region_id => 68)
  #DictionaryCity.create(:name => 'Саяногорск', :dictionary_region_id => 68)
  #DictionaryCity.create(:name => 'Сорск', :dictionary_region_id => 68)
  #DictionaryCity.create(:name => 'Черногорск', :dictionary_region_id => 68)

  #DictionaryCity.create(:name => 'Алейск', :dictionary_region_id => 67)
  #DictionaryCity.create(:name => 'Барнаул', :dictionary_region_id => 67)
  #DictionaryCity.create(:name => 'Белокуриха', :dictionary_region_id => 67)
  #DictionaryCity.create(:name => 'Бийск', :dictionary_region_id => 67)
  #DictionaryCity.create(:name => 'Горняк', :dictionary_region_id => 67)
  #DictionaryCity.create(:name => 'Заринск', :dictionary_region_id => 67)
  #DictionaryCity.create(:name => 'Змеиногорск', :dictionary_region_id => 67)
  #DictionaryCity.create(:name => 'Камень-на-Оби', :dictionary_region_id => 67)
  #DictionaryCity.create(:name => 'Новоалтайск', :dictionary_region_id => 67)
  #DictionaryCity.create(:name => 'Рубцовск', :dictionary_region_id => 67)
  #DictionaryCity.create(:name => 'Славгород', :dictionary_region_id => 67)
  #DictionaryCity.create(:name => 'Яровое', :dictionary_region_id => 67)

  #DictionaryCity.create(:name => 'Балей', :dictionary_region_id => 66)
  #DictionaryCity.create(:name => 'Борзя', :dictionary_region_id => 66)
  #DictionaryCity.create(:name => 'Краснокаменск', :dictionary_region_id => 66)
  #DictionaryCity.create(:name => 'Могоча', :dictionary_region_id => 66)
  #DictionaryCity.create(:name => 'Нерчинск', :dictionary_region_id => 66)
  #DictionaryCity.create(:name => 'Петровск-Забайкальский', :dictionary_region_id => 66)
  #DictionaryCity.create(:name => 'Сретенск', :dictionary_region_id => 66)
  #DictionaryCity.create(:name => 'Хилок', :dictionary_region_id => 66)
  #DictionaryCity.create(:name => 'Чита', :dictionary_region_id => 66)
  #DictionaryCity.create(:name => 'Шилка', :dictionary_region_id => 66)

  #DictionaryCity.create(:name => 'Артёмовск', :dictionary_region_id => 65)
  #DictionaryCity.create(:name => 'Ачинск', :dictionary_region_id => 65)
  #DictionaryCity.create(:name => 'Боготол', :dictionary_region_id => 65)
  #DictionaryCity.create(:name => 'Бородино', :dictionary_region_id => 65)
  #DictionaryCity.create(:name => 'Дивногорск', :dictionary_region_id => 65)
  #DictionaryCity.create(:name => 'Дудинка', :dictionary_region_id => 65)
  #DictionaryCity.create(:name => 'Енисейск', :dictionary_region_id => 65)
  #DictionaryCity.create(:name => 'Заозёрный', :dictionary_region_id => 65)
  #DictionaryCity.create(:name => 'Зеленогорск', :dictionary_region_id => 65)
  #DictionaryCity.create(:name => 'Игарка', :dictionary_region_id => 65)
  #DictionaryCity.create(:name => 'Иланский', :dictionary_region_id => 65)
  #DictionaryCity.create(:name => 'Канск', :dictionary_region_id => 65)
  #DictionaryCity.create(:name => 'Кодинск', :dictionary_region_id => 65)
  #DictionaryCity.create(:name => 'Красноярск', :dictionary_region_id => 65)
  #DictionaryCity.create(:name => 'Лесосибирск', :dictionary_region_id => 65)
  #DictionaryCity.create(:name => 'Минусинск', :dictionary_region_id => 65)
  #DictionaryCity.create(:name => 'Назарово', :dictionary_region_id => 65)
  #DictionaryCity.create(:name => 'Норильск', :dictionary_region_id => 65)
  #DictionaryCity.create(:name => 'Сосновоборск', :dictionary_region_id => 65)
  #DictionaryCity.create(:name => 'Ужур', :dictionary_region_id => 65)
  #DictionaryCity.create(:name => 'Уяр', :dictionary_region_id => 65)
  #DictionaryCity.create(:name => 'Шарыпово', :dictionary_region_id => 65)
  #DictionaryCity.create(:name => 'Железногорск', :dictionary_region_id => 65)

  #DictionaryCity.create(:name => 'Алзамай', :dictionary_region_id => 64)
  #DictionaryCity.create(:name => 'Ангарск', :dictionary_region_id => 64)
  #DictionaryCity.create(:name => 'Байкальск', :dictionary_region_id => 64)
  #DictionaryCity.create(:name => 'Бирюсинск', :dictionary_region_id => 64)
  #DictionaryCity.create(:name => 'Бодайбо', :dictionary_region_id => 64)
  #DictionaryCity.create(:name => 'Братск', :dictionary_region_id => 64)
  #DictionaryCity.create(:name => 'Вихоревка', :dictionary_region_id => 64)
  #DictionaryCity.create(:name => 'Железногорск-Илимский', :dictionary_region_id => 64)
  #DictionaryCity.create(:name => 'Зима', :dictionary_region_id => 64)
  #DictionaryCity.create(:name => 'Иркутск', :dictionary_region_id => 64)
  #DictionaryCity.create(:name => 'Киренск', :dictionary_region_id => 64)
  #DictionaryCity.create(:name => 'Нижнеудинск', :dictionary_region_id => 64)
  #DictionaryCity.create(:name => 'Саянск', :dictionary_region_id => 64)
  #DictionaryCity.create(:name => 'Свирск', :dictionary_region_id => 64)
  #DictionaryCity.create(:name => 'Слюдянка', :dictionary_region_id => 64)
  #DictionaryCity.create(:name => 'Тайшет', :dictionary_region_id => 64)
  #DictionaryCity.create(:name => 'Тулун', :dictionary_region_id => 64)
  #DictionaryCity.create(:name => 'Усолье-Сибирское', :dictionary_region_id => 64)
  #DictionaryCity.create(:name => 'Усть-Илимск', :dictionary_region_id => 64)
  #DictionaryCity.create(:name => 'Усть-Кут', :dictionary_region_id => 64)
  #DictionaryCity.create(:name => 'Черемхово', :dictionary_region_id => 64)
  #DictionaryCity.create(:name => 'Шелехов', :dictionary_region_id => 64)

  #DictionaryCity.create(:name => 'Анжеро-Судженск', :dictionary_region_id => 62)
  #DictionaryCity.create(:name => 'Белово', :dictionary_region_id => 62)
  #DictionaryCity.create(:name => 'Калтан', :dictionary_region_id => 62)
  #DictionaryCity.create(:name => 'Кемерово', :dictionary_region_id => 62)
  #DictionaryCity.create(:name => 'Киселёвск', :dictionary_region_id => 62)
  #DictionaryCity.create(:name => 'Ленинск-Кузнецкий', :dictionary_region_id => 62)
  #DictionaryCity.create(:name => 'Мариинск', :dictionary_region_id => 62)
  #DictionaryCity.create(:name => 'Междуреченск', :dictionary_region_id => 62)
  #DictionaryCity.create(:name => 'Мыски', :dictionary_region_id => 62)
  #DictionaryCity.create(:name => 'Новокузнецк', :dictionary_region_id => 62)
  #DictionaryCity.create(:name => 'Осинники', :dictionary_region_id => 62)
  #DictionaryCity.create(:name => 'Полысаево', :dictionary_region_id => 62)
  #DictionaryCity.create(:name => 'Прокопьевск', :dictionary_region_id => 62)
  #DictionaryCity.create(:name => 'Салаир', :dictionary_region_id => 62)
  #DictionaryCity.create(:name => 'Тайга', :dictionary_region_id => 62)
  #DictionaryCity.create(:name => 'Таштагол', :dictionary_region_id => 62)
  #DictionaryCity.create(:name => 'Топки', :dictionary_region_id => 62)
  #DictionaryCity.create(:name => 'Юрга', :dictionary_region_id => 62)
  #DictionaryCity.create(:name => 'Березовский', :dictionary_region_id => 62)
  #DictionaryCity.create(:name => 'Гурьевск', :dictionary_region_id => 62)

  #DictionaryCity.create(:name => 'Барабинск', :dictionary_region_id => 63)
  #DictionaryCity.create(:name => 'Бердск', :dictionary_region_id => 63)
  #DictionaryCity.create(:name => 'Болотное', :dictionary_region_id => 63)
  #DictionaryCity.create(:name => 'Искитим', :dictionary_region_id => 63)
  #DictionaryCity.create(:name => 'Карасук', :dictionary_region_id => 63)
  #DictionaryCity.create(:name => 'Каргат', :dictionary_region_id => 63)
  #DictionaryCity.create(:name => 'Куйбышев', :dictionary_region_id => 63)
  #DictionaryCity.create(:name => 'Купино', :dictionary_region_id => 63)
  #DictionaryCity.create(:name => 'Новосибирск', :dictionary_region_id => 63)
  #DictionaryCity.create(:name => 'Обь', :dictionary_region_id => 63)
  #DictionaryCity.create(:name => 'Татарск', :dictionary_region_id => 63)
  #DictionaryCity.create(:name => 'Тогучин', :dictionary_region_id => 63)
  #DictionaryCity.create(:name => 'Черепаново', :dictionary_region_id => 63)
  #DictionaryCity.create(:name => 'Чулым', :dictionary_region_id => 63)

  #DictionaryCity.create(:name => 'Исилькуль', :dictionary_region_id => 61)
  #DictionaryCity.create(:name => 'Калачинск', :dictionary_region_id => 61)
  #DictionaryCity.create(:name => 'Называевск', :dictionary_region_id => 61)
  #DictionaryCity.create(:name => 'Омск', :dictionary_region_id => 61)
  #DictionaryCity.create(:name => 'Тара', :dictionary_region_id => 61)
  #DictionaryCity.create(:name => 'Тюкалинск', :dictionary_region_id => 61)

  #DictionaryCity.create(:name => 'Асино', :dictionary_region_id => 79)
  #DictionaryCity.create(:name => 'Кедровый', :dictionary_region_id => 79)
  #DictionaryCity.create(:name => 'Колпашево', :dictionary_region_id => 79)
  #DictionaryCity.create(:name => 'Северск', :dictionary_region_id => 79)
  #DictionaryCity.create(:name => 'Стрежевой', :dictionary_region_id => 79)
  #DictionaryCity.create(:name => 'Томск', :dictionary_region_id => 79)

  #DictionaryCity.create(:name => 'Вилюйск', :dictionary_region_id => 80)
  #DictionaryCity.create(:name => 'Ленск', :dictionary_region_id => 80)
  #DictionaryCity.create(:name => 'Нерюнгри', :dictionary_region_id => 80)
  #DictionaryCity.create(:name => 'Нюрба', :dictionary_region_id => 80)
  #DictionaryCity.create(:name => 'Олёкминск', :dictionary_region_id => 80)
  #DictionaryCity.create(:name => 'Покровск', :dictionary_region_id => 80)
  #DictionaryCity.create(:name => 'Среднеколымск', :dictionary_region_id => 80)
  #DictionaryCity.create(:name => 'Томмот', :dictionary_region_id => 80)
  #DictionaryCity.create(:name => 'Удачный', :dictionary_region_id => 80)
  #DictionaryCity.create(:name => 'Якутск', :dictionary_region_id => 80)
  #DictionaryCity.create(:name => 'Мирный', :dictionary_region_id => 80)
  #DictionaryCity.create(:name => 'Алдан', :dictionary_region_id => 80)
  #DictionaryCity.create(:name => 'Верхоярск', :dictionary_region_id => 80)

  #DictionaryCity.create(:name => 'Вилючинск', :dictionary_region_id => 81)
  #DictionaryCity.create(:name => 'Елизово', :dictionary_region_id => 81)
  #DictionaryCity.create(:name => 'Петропавловск-Камчатский', :dictionary_region_id => 81)

  #DictionaryCity.create(:name => 'Арсеньев', :dictionary_region_id => 76)
  #DictionaryCity.create(:name => 'Артём', :dictionary_region_id => 76)
  #DictionaryCity.create(:name => 'Большой Камень', :dictionary_region_id => 76)
  #DictionaryCity.create(:name => 'Владивосток', :dictionary_region_id => 76)
  #DictionaryCity.create(:name => 'Дальнегорск', :dictionary_region_id => 76)
  #DictionaryCity.create(:name => 'Дальнереченск', :dictionary_region_id => 76)
  #DictionaryCity.create(:name => 'Лесозаводск', :dictionary_region_id => 76)
  #DictionaryCity.create(:name => 'Находка', :dictionary_region_id => 76)
  #DictionaryCity.create(:name => 'Партизанск', :dictionary_region_id => 76)
  #DictionaryCity.create(:name => 'Спасск-Дальний', :dictionary_region_id => 76)
  #DictionaryCity.create(:name => 'Уссурийск', :dictionary_region_id => 76)
  #DictionaryCity.create(:name => 'Фокино', :dictionary_region_id => 76)

  #DictionaryCity.create(:name => 'Амурск', :dictionary_region_id => 77)
  #DictionaryCity.create(:name => 'Бикин', :dictionary_region_id => 77)
  #DictionaryCity.create(:name => 'Вяземский', :dictionary_region_id => 77)
  #DictionaryCity.create(:name => 'Комсомольск-на-Амуре', :dictionary_region_id => 77)
  #DictionaryCity.create(:name => 'Николаевск-на-Амуре', :dictionary_region_id => 77)
  #DictionaryCity.create(:name => 'Советская Гавань', :dictionary_region_id => 77)
  #DictionaryCity.create(:name => 'Хабаровск', :dictionary_region_id => 77)

  #DictionaryCity.create(:name => 'Белогорск', :dictionary_region_id => 78)
  #DictionaryCity.create(:name => 'Завитинск', :dictionary_region_id => 78)
  #DictionaryCity.create(:name => 'Зея', :dictionary_region_id => 78)
  #DictionaryCity.create(:name => 'Райчихинск', :dictionary_region_id => 78)
  #DictionaryCity.create(:name => 'Свободный', :dictionary_region_id => 78)
  #DictionaryCity.create(:name => 'Сковородино', :dictionary_region_id => 78)
  #DictionaryCity.create(:name => 'Тында', :dictionary_region_id => 78)
  #DictionaryCity.create(:name => 'Шимановск', :dictionary_region_id => 78)
  #DictionaryCity.create(:name => 'Благовещенск', :dictionary_region_id => 78)

  #DictionaryCity.create(:name => 'Магадан', :dictionary_region_id => 75)
  #DictionaryCity.create(:name => 'Сусуман', :dictionary_region_id => 75)

  #DictionaryCity.create(:name => 'Александровск-Сахалинский', :dictionary_region_id => 73)
  #DictionaryCity.create(:name => 'Анива', :dictionary_region_id => 73)
  #DictionaryCity.create(:name => 'Долинск', :dictionary_region_id => 73)
  #DictionaryCity.create(:name => 'Корсаков', :dictionary_region_id => 73)
  #DictionaryCity.create(:name => 'Курильск', :dictionary_region_id => 73)
  #DictionaryCity.create(:name => 'Макаров', :dictionary_region_id => 73)
  #DictionaryCity.create(:name => 'Невельск', :dictionary_region_id => 73)
  #DictionaryCity.create(:name => 'Оха', :dictionary_region_id => 73)
  #DictionaryCity.create(:name => 'Поронайск', :dictionary_region_id => 73)
  #DictionaryCity.create(:name => 'Северо-Курильск', :dictionary_region_id => 73)
  #DictionaryCity.create(:name => 'Томари', :dictionary_region_id => 73)
  #DictionaryCity.create(:name => 'Углегорск', :dictionary_region_id => 73)
  #DictionaryCity.create(:name => 'Холмск', :dictionary_region_id => 73)
  #DictionaryCity.create(:name => 'Шахтёрск', :dictionary_region_id => 73)
  #DictionaryCity.create(:name => 'Южно-Сахалинск', :dictionary_region_id => 73)

  #DictionaryCity.create(:name => 'Биробиджан', :dictionary_region_id => 74)
  #DictionaryCity.create(:name => 'Облучье', :dictionary_region_id => 74)

  #DictionaryCity.create(:name => 'Анадырь', :dictionary_region_id => 72)
  #DictionaryCity.create(:name => 'Билибино', :dictionary_region_id => 72)
  #DictionaryCity.create(:name => 'Певек', :dictionary_region_id => 72)
end
